In [1]:
import numpy as np
import torch

In [2]:
import gym

In [3]:
env = gym.make("InvertedPendulum-v2")

In [4]:
env.reset()

array([-0.00101211,  0.00081362,  0.00170734,  0.0062294 ])

In [5]:
a = env.action_space.sample()

In [6]:
state, _, _, _ = env.step(a) 
state

array([-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ])

In [7]:
action = env.action_space.sample()
next_state, reward, done, _ = env.step(action)
action

array([-1.7503828], dtype=float32)

In [8]:
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.shape[0] 
action_low = env.action_space.low[0]
action_high = env.action_space.high[0]
state_low = env.observation_space.low
state_high = env.observation_space.high

max_action = float(action_high)
print(f"state low, high: {state_low, state_high}  action low, high: {action_low, action_high}")

state low, high: (array([-inf, -inf, -inf, -inf]), array([inf, inf, inf, inf]))  action low, high: (-3.0, 3.0)


In [23]:
def normalize_action(x):
    return (x-action_low)/(action_high-action_low)

# TODO find a way to scale this
def normalize_state(s):
    return s
def normalize_reward(r):
    return np.array([r/20.0])


In [25]:
# data = torch.Tensor(np.concatenate((state, action, next_state, np.array([reward]), np.array([done]))))     
data = np.concatenate((normalize_state(state), normalize_action(action), normalize_state(next_state), normalize_reward(reward), np.array([done])))
# normalize_state(state)
data

array([-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
       -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
        0.        ])

In [31]:
datas = [data, data, data]
datas

[array([-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
        -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
         0.        ]),
 array([-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
        -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
         0.        ]),
 array([-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
        -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
         0.        ])]

In [29]:
d = np.array([i for i in datas])

tensor([[-0.0161,  0.0366, -0.7525,  1.7615,  0.2083, -0.0588,  0.1353, -1.3801,
          3.1705,  0.0500,  0.0000],
        [-0.0161,  0.0366, -0.7525,  1.7615,  0.2083, -0.0588,  0.1353, -1.3801,
          3.1705,  0.0500,  0.0000],
        [-0.0161,  0.0366, -0.7525,  1.7615,  0.2083, -0.0588,  0.1353, -1.3801,
          3.1705,  0.0500,  0.0000]])

In [32]:
d[0]

array([-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
       -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
        0.        ])

In [46]:
# Save data
def save_data():
    res = []
    for da in datas:
        res.append(da)
    print(res)
    np.save("env.npy", res)

    

In [47]:
save_data()

[array([-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
       -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
        0.        ]), array([-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
       -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
        0.        ]), array([-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
       -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
        0.        ])]


In [48]:
saved = np.load("env.npy", allow_pickle=True)
saved

array([[-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
        -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
         0.        ],
       [-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
        -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
         0.        ],
       [-0.0160772 ,  0.03655668, -0.75253633,  1.761529  ,  0.20826954,
        -0.05876967,  0.13533287, -1.38006406,  3.17047549,  0.05      ,
         0.        ]])

In [49]:
x = torch.Tensor(saved)

In [50]:
x

tensor([[-0.0161,  0.0366, -0.7525,  1.7615,  0.2083, -0.0588,  0.1353, -1.3801,
          3.1705,  0.0500,  0.0000],
        [-0.0161,  0.0366, -0.7525,  1.7615,  0.2083, -0.0588,  0.1353, -1.3801,
          3.1705,  0.0500,  0.0000],
        [-0.0161,  0.0366, -0.7525,  1.7615,  0.2083, -0.0588,  0.1353, -1.3801,
          3.1705,  0.0500,  0.0000]])

In [51]:
x[0]

tensor([-0.0161,  0.0366, -0.7525,  1.7615,  0.2083, -0.0588,  0.1353, -1.3801,
         3.1705,  0.0500,  0.0000])

In [55]:
env.env.state

AttributeError: 'InvertedPendulumEnv' object has no attribute 'state'