In [7]:
import numpy as np
import torch
import gym
from tqdm import tqdm

In [8]:
env = gym.make("InvertedPendulum-v2")
env.reset()

array([-9.62860830e-03, -6.45766131e-05, -6.05014803e-03, -1.03937720e-04])

In [20]:
AMOUNT = 100000
FILE_NAME = "testing.npy"

In [36]:
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.shape[0] 
action_low = env.action_space.low[0]
action_high = env.action_space.high[0]
state_low = env.observation_space.low
state_high = env.observation_space.high

print(state_low)
def normalize_action(x):
    return (x-action_low)/(action_high-action_low)
# TODO find a way to scale this
def normalize_state(s):
    return s
def normalize_reward(r):
    return np.array([r/20.0])

[-inf -inf -inf -inf]


In [22]:
raw = []
a = env.action_space.sample()
old_state, _, _, _ = env.step(a) 
dones = 0
for i in tqdm(range(AMOUNT)):
    a = env.action_space.sample()
    s, r, d, _ = env.step(a)
    raw.append(np.concatenate((normalize_state(old_state), normalize_action(a), normalize_state(s), normalize_reward(r), np.array([d]))))
    if d:
        dones += 1
        old_state = env.reset()
print(dones)
    
               
               

    

100%|██████████| 100000/100000 [00:12<00:00, 8191.30it/s]

17492


In [23]:
raw[345]

array([-0.00444569, -0.00802593,  0.00954695, -0.00953664,  0.2204126 ,
       -0.01714233,  0.04401365,  0.19700072, -0.03321564,  0.05      ,
        0.        ])

In [24]:
np.save(FILE_NAME, raw)

In [25]:
saved = np.load(FILE_NAME, allow_pickle=True)

In [27]:
saved[345]

array([-0.00444569, -0.00802593,  0.00954695, -0.00953664,  0.2204126 ,
       -0.01714233,  0.04401365,  0.19700072, -0.03321564,  0.05      ,
        0.        ])

In [28]:
x = torch.Tensor(saved)

In [29]:
x[345]

tensor([-0.0044, -0.0080,  0.0095, -0.0095,  0.2204, -0.0171,  0.0440,  0.1970,
        -0.0332,  0.0500,  0.0000])

In [33]:
x = "absadcds"
x[2:]
# x[:2]

'sadcds'